// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt

#include "../ui.h"

void ui_ScreenListen_screen_init(void)
{
    ui_ScreenListen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenListen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // Use theme color background instead of image - dark background with subtle gradient
    lv_obj_set_style_bg_color(ui_ScreenListen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenListen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenListen, lv_color_hex(0x1a1a2e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenListen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Removed unused ImageBodyShadow object

    ui_PanelSleep = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelSleep, 320);
    lv_obj_set_height(ui_PanelSleep, 240);
    lv_obj_clear_flag(ui_PanelSleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSleep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // Replace individual body/eye images with single sleep_mode image
    ui_ImageSleepBody = lv_img_create(ui_PanelSleep);
    lv_img_set_src(ui_ImageSleepBody, &ui_img_sleep_mode_png);
    lv_obj_set_width(ui_ImageSleepBody, 320);   /// Full screen width
    lv_obj_set_height(ui_ImageSleepBody, 240);    /// Full screen height
    lv_obj_set_x(ui_ImageSleepBody, 20);  /// Move 20px to the right
    lv_obj_set_align(ui_ImageSleepBody, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSleepBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageSleepBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_ImageSleepBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ImageSleepBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ImageSleepBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Removed unused Image3 and ImageSleepEye objects (replaced by sleep_mode image)

    ui_ContainerBigZ = lv_obj_create(ui_PanelSleep);
    lv_obj_set_width(ui_ContainerBigZ, 27);
    lv_obj_set_height(ui_ContainerBigZ, 22);
    lv_obj_set_x(ui_ContainerBigZ, 83);
    lv_obj_set_y(ui_ContainerBigZ, -28);
    lv_obj_set_align(ui_ContainerBigZ, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerBigZ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerBigZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerBigZ, &ui_img_sleep_big_z_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerBigZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContainerBigZ, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ContainerSmallZ = lv_obj_create(ui_PanelSleep);
    lv_obj_set_width(ui_ContainerSmallZ, 23);
    lv_obj_set_height(ui_ContainerSmallZ, 17);
    lv_obj_set_x(ui_ContainerSmallZ, 106);
    lv_obj_set_y(ui_ContainerSmallZ, -34);
    lv_obj_set_align(ui_ContainerSmallZ, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSmallZ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerSmallZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerSmallZ, &ui_img_sleep_small_z_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerSmallZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContainerSmallZ, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PanelListen = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelListen, 320);
    lv_obj_set_height(ui_PanelListen, 240);
    lv_obj_add_flag(ui_PanelListen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelListen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelListen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // Removed unused ImageListenBackGlow object (unwanted background)
    
    // Create avatar as direct child of panel
    ui_ImageListenBody = lv_img_create(ui_PanelListen);
    lv_img_set_src(ui_ImageListenBody, &ui_img_avatar_avatar_0_png);  // Start with first frame
    lv_obj_set_width(ui_ImageListenBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageListenBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageListenBody, 0);
    lv_obj_set_y(ui_ImageListenBody, 0);
    lv_obj_set_align(ui_ImageListenBody, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageListenBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageListenBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Removed unused ImageListenEyeScreen and ImageListenEye objects (replaced by animated avatar)

    ui_PanelGet = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelGet, 320);
    lv_obj_set_height(ui_PanelGet, 240);
    lv_obj_add_flag(ui_PanelGet, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelGet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // Removed unused ImageGetBackGlow object (unwanted background)
    
    // Create avatar as direct child of panel
    ui_ImageGetBody = lv_img_create(ui_PanelGet);
    lv_img_set_src(ui_ImageGetBody, &ui_img_avatar_avatar_0_png);  // Start with first frame
    lv_obj_set_width(ui_ImageGetBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetBody, 0);
    lv_obj_set_y(ui_ImageGetBody, 0);
    lv_obj_set_align(ui_ImageGetBody, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageGetBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Removed unused ImageGetEyeScreen and ImageGetEye objects (replaced by animated avatar)

    ui_PanelReply = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelReply, 320);
    lv_obj_set_height(ui_PanelReply, 240);
    lv_obj_add_flag(ui_PanelReply, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelReply, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelReply, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // Replace reply background image with styled panel using theme colors
    ui_ImageReplyBg = lv_obj_create(ui_PanelReply);
    lv_obj_set_width(ui_ImageReplyBg, 280);
    lv_obj_set_height(ui_ImageReplyBg, 35);
    lv_obj_set_x(ui_ImageReplyBg, 0);
    lv_obj_set_y(ui_ImageReplyBg, 5);
    lv_obj_set_align(ui_ImageReplyBg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImageReplyBg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_HIDDEN);     /// Flags - Hide question text
    lv_obj_clear_flag(ui_ImageReplyBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // Style with theme colors - green background with rounded corners
    lv_obj_set_style_radius(ui_ImageReplyBg, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImageReplyBg, lv_color_hex(0x04B900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageReplyBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageReplyBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ImageReplyBg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ImageReplyBg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ImageReplyBg, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ImageReplyBg, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReplyQuestion = lv_label_create(ui_ImageReplyBg);
    lv_obj_set_width(ui_LabelReplyQuestion, 205);
    lv_obj_set_height(ui_LabelReplyQuestion, 25);
    lv_obj_set_x(ui_LabelReplyQuestion, 20);
    lv_obj_set_y(ui_LabelReplyQuestion, -1);
    lv_obj_set_align(ui_LabelReplyQuestion, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_LabelReplyQuestion, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelReplyQuestion, "");
    lv_obj_clear_flag(ui_LabelReplyQuestion, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scroll_dir(ui_LabelReplyQuestion, LV_DIR_HOR);
    lv_obj_set_style_text_color(ui_LabelReplyQuestion, lv_color_hex(0xD24B09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReplyQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelReplyQuestion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelReplyQuestion, &ui_font_KaiTiCN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Replace reply body with animated avatar image collection
    ui_ImageRelyBody = lv_img_create(ui_PanelReply);
    lv_img_set_src(ui_ImageRelyBody, &ui_img_avatar_avatar_0_png);  // Start with first frame
    lv_obj_set_width(ui_ImageRelyBody, LV_SIZE_CONTENT);   /// Auto size
    lv_obj_set_height(ui_ImageRelyBody, LV_SIZE_CONTENT);    /// Auto size
    lv_obj_set_x(ui_ImageRelyBody, 0);
    lv_obj_set_y(ui_ImageRelyBody, 0);
    lv_obj_set_align(ui_ImageRelyBody, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRelyBody, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRelyBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Removed unused ImageReplyBodyShadow object

    ui_ContainerReplyContent = lv_obj_create(ui_PanelReply);
    lv_obj_set_height(ui_ContainerReplyContent, 160);
    lv_obj_set_width(ui_ContainerReplyContent, LV_SIZE_CONTENT);   /// 268
    lv_obj_set_x(ui_ContainerReplyContent, -20);
    lv_obj_set_y(ui_ContainerReplyContent, 60);
    lv_obj_set_align(ui_ContainerReplyContent, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_scroll_dir(ui_ContainerReplyContent, LV_DIR_VER);
    lv_obj_add_flag(ui_ContainerReplyContent, LV_OBJ_FLAG_HIDDEN);     /// Hide answer text - only show animation
    lv_obj_set_style_radius(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerReplyContent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerReplyContent, &ui_img_sleep_big_z_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContainerReplyContent, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelReplyContent = lv_label_create(ui_ContainerReplyContent);
    lv_obj_set_width(ui_LabelReplyContent, 250);
    lv_obj_set_height(ui_LabelReplyContent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReplyContent, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelReplyContent, "");
    lv_obj_set_style_text_color(ui_LabelReplyContent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReplyContent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelReplyContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelReplyContent, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelReplyContent, &ui_font_KaiTiCN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Removed unused ImageReplyLogo object

    ui_LabelListenSpeak = lv_label_create(ui_ScreenListen);
    lv_obj_set_width(ui_LabelListenSpeak, 260);  // Width for better text display
    lv_obj_set_height(ui_LabelListenSpeak, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelListenSpeak, 0);
    lv_obj_set_y(ui_LabelListenSpeak, -20);  // Move a bit further down
    lv_obj_set_align(ui_LabelListenSpeak, LV_ALIGN_BOTTOM_MID);
    // Show full STT/response text with wrapping (no truncation)
    lv_label_set_long_mode(ui_LabelListenSpeak, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_LabelListenSpeak, "");
    lv_obj_add_flag(ui_LabelListenSpeak, LV_OBJ_FLAG_HIDDEN);     /// Flags
    // No manual scrolling flags needed for circular label scroll
    lv_obj_set_style_text_color(ui_LabelListenSpeak, lv_color_hex(0xD24B09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelListenSpeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelListenSpeak, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelListenSpeak, &ui_font_KaiTiCN20, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Remove all border and background styling - text only
    lv_obj_set_style_bg_opa(ui_LabelListenSpeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelListenSpeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_LabelListenSpeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelSleep, ui_event_PanelSleep, LV_EVENT_ALL, NULL);

}
