// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt

#include "ui.h"
#include "ui_helpers.h"
#include <stdio.h>

///////////////////// VARIABLES ////////////////////
int check;
// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
lv_obj_t *ui_ScreenSetup;
lv_obj_t *ui_ImageSetupTextBg;
lv_obj_t *ui_PanelSetupWifi;
lv_obj_t *ui_LabelSetupWifi;
void ui_event_ImageSetupWifiReset(lv_event_t *e);
lv_obj_t *ui_ImageSetupWifiReset;
lv_obj_t *ui_PanelSetupSteps;
lv_obj_t *ui_LabelSetupStepContent;
lv_obj_t *ui_LabelSetupStepTile;
void ui_event_ButtonSetup(lv_event_t *e);
lv_obj_t *ui_ButtonSetup;
lv_obj_t *ui_LabelSetupBtn;

// SCREEN: ui_ScreenWifiReset
void ui_ScreenWifiReset_screen_init(void);
lv_obj_t *ui_ScreenWifiReset;
lv_obj_t *ui_LabelWifiResetTitle;
void ui_event_ButtonWifiResetConfirm(lv_event_t *e);
lv_obj_t *ui_ButtonWifiResetConfirm;
lv_obj_t *ui_LabelSetupBtn1;
void ui_event_ImageWifiResetBack(lv_event_t *e);
lv_obj_t *ui_ImageWifiResetBack;
lv_obj_t *ui_LabelWifiResetContent;

// SCREEN: ui_ScreenListen
void ui_ScreenListen_screen_init(void);
lv_obj_t *ui_ScreenListen;
void ui_event_PanelSleep(lv_event_t *e);
lv_obj_t *ui_PanelSleep;
lv_obj_t *ui_ImageSleepBody;
lv_obj_t *ui_ContainerBigZ;
lv_obj_t *ui_ContainerSmallZ;
lv_obj_t *ui_PanelListen;
lv_obj_t *ui_ImageListenBody;
lv_obj_t *ui_PanelGet;
lv_obj_t *ui_ImageGetBody;
lv_obj_t *ui_PanelReply;
lv_obj_t *ui_ImageReplyBg;
lv_obj_t *ui_LabelReplyQuestion;
lv_obj_t *ui_ImageRelyBody;
lv_obj_t *ui_ContainerReplyContent;
lv_obj_t *ui_LabelReplyContent;
lv_obj_t *ui_LabelListenSpeak;

// SCREEN: ui_ScreenReset
void ui_ScreenReset_screen_init(void);
lv_obj_t *ui_ScreenReset;
lv_obj_t *ui_LabelResetTitle;
lv_obj_t *ui_LabelResetContent;
void ui_event_ButtonResetConfirm(lv_event_t *e);
lv_obj_t *ui_ButtonResetConfirm;
lv_obj_t *ui_LabelSetupBtn2;
void ui_event_ImageResetBack(lv_event_t *e);
lv_obj_t *ui_ImageResetBack;
void ui_event____initial_actions0(lv_event_t *e);
lv_obj_t *ui____initial_actions0;
// Image sets for animated avatar collections
// Animation frames: 6 frames for speaker (0-5), 6 frames for avatar (0-5)
const lv_img_dsc_t *ui_imgset_speaker_[6] = {
    &ui_img_speaker_speaker_0_png, &ui_img_speaker_speaker_1_png, &ui_img_speaker_speaker_2_png,
    &ui_img_speaker_speaker_3_png, &ui_img_speaker_speaker_4_png, &ui_img_speaker_speaker_5_png
};
const lv_img_dsc_t *ui_imgset_avatar_[6] = {
    &ui_img_avatar_avatar_0_png, &ui_img_avatar_avatar_1_png, &ui_img_avatar_avatar_2_png,
    &ui_img_avatar_avatar_3_png, &ui_img_avatar_avatar_4_png, &ui_img_avatar_avatar_5_png
};


static lv_group_t *g_btn_op_group = NULL;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

lv_group_t *ui_get_btn_op_group(void)
{
    return g_btn_op_group;
}

///////////////////// ANIMATIONS ////////////////////
// Old animation functions removed - replaced with avatar/speaker animations

// Animation function for speaker (when audio/TTS is playing)
void avatar_speaking_Animation(lv_obj_t *TargetObject, int delay)
{
    if (!TargetObject) return;
    
    // Stop ALL animations first - force complete cleanup
    lv_anim_del(NULL, NULL);
    
    // Small delay to ensure animations are fully stopped
    lv_timer_handler();
    
    // Reset image to first frame of speaker animation
    lv_img_set_src(TargetObject, &ui_img_speaker_speaker_0_png);
    
    // Force immediate refresh
    lv_obj_invalidate(TargetObject);
    
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_speaker_;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_speaker_) / sizeof(lv_img_dsc_t *);
    PropertyAnimation_0_user_data->val = -1;
    
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_var(&PropertyAnimation_0, TargetObject);  // Set target object
    lv_anim_set_time(&PropertyAnimation_0, 1500);  // 1.5 seconds - slower speaking animation
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 5);  // 6 frames (0-5) - reduced from 7 due to binary size
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame);
    
    lv_anim_start(&PropertyAnimation_0);
}

// Animation function for avatar (when listening, no audio playing)
void avatar_listening_Animation(lv_obj_t *TargetObject, int delay)
{
    if (!TargetObject) return;
    
    // Stop ALL animations first - force complete cleanup
    lv_anim_del(NULL, NULL);
    
    // Small delay to ensure animations are fully stopped
    lv_timer_handler();
    
    // Reset image to first frame of avatar animation
    lv_img_set_src(TargetObject, &ui_img_avatar_avatar_0_png);
    
    // Force immediate refresh
    lv_obj_invalidate(TargetObject);
    
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_avatar_;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_avatar_) / sizeof(lv_img_dsc_t *);
    PropertyAnimation_0_user_data->val = -1;
    
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_var(&PropertyAnimation_0, TargetObject);  // Set target object
    lv_anim_set_time(&PropertyAnimation_0, 1500);  // 1.5 seconds - slower listening animation
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 5);  // 6 frames (0-5) - reduced from 7 due to binary size
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame);
    
    lv_anim_start(&PropertyAnimation_0);
}

// Function to stop avatar animations for all panels
void avatar_stop_animations(void)
{
    // Stop ALL animations globally to prevent any mixing
    lv_anim_del(NULL, NULL);
    
    // Process any pending animations
    lv_timer_handler();
    
    // Reset all images to avatar frame 0 to prevent mixed animations
    if (ui_ImageListenBody) {
        lv_img_set_src(ui_ImageListenBody, &ui_img_avatar_avatar_0_png);
        lv_obj_invalidate(ui_ImageListenBody);
    }
    if (ui_ImageGetBody) {
        lv_img_set_src(ui_ImageGetBody, &ui_img_avatar_avatar_0_png);
        lv_obj_invalidate(ui_ImageGetBody);
    }
    if (ui_ImageRelyBody) {
        lv_img_set_src(ui_ImageRelyBody, &ui_img_avatar_avatar_0_png);
        lv_obj_invalidate(ui_ImageRelyBody);
    }
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ImageSetupWifiReset(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ScreenWifiReset, LV_SCR_LOAD_ANIM_NONE, 0, 0);
        if (ui_get_btn_op_group()) {
            lv_group_remove_all_objs(ui_get_btn_op_group());
            lv_group_add_obj(ui_get_btn_op_group(), ui_ButtonWifiResetConfirm);
            lv_group_add_obj(ui_get_btn_op_group(), ui_ImageWifiResetBack);
        }
    }
}

void ui_event_ButtonSetup(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ScreenListen, LV_SCR_LOAD_ANIM_NONE, 0, 0);

        if (ui_get_btn_op_group()) {
            lv_group_remove_all_objs(ui_get_btn_op_group());
            lv_group_add_obj(ui_get_btn_op_group(), ui_PanelSleep);
        }

        // Old animations removed - replaced with animated avatar collections
        EventBtnSetupClick(e);
        _ui_flag_modify(ui_PanelSleep, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanelListen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PanelGet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PanelReply, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ButtonWifiResetConfirm(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        EventWifiResetConfirmClick(e);
    }
}

void ui_event_ImageWifiResetBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ScreenSetup, LV_SCR_LOAD_ANIM_NONE, 0, 0);
        if (ui_get_btn_op_group()) {
            lv_group_remove_all_objs(ui_get_btn_op_group());
            lv_group_add_obj(ui_get_btn_op_group(), ui_ImageSetupWifiReset);
        }
    }
}

void ui_event_PanelSleep(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (true == lv_obj_has_flag(ui_PanelSleep, LV_OBJ_FLAG_HIDDEN)) {
        return;
    }
    if (event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_flag_modify(ui_PanelListen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanelSleep, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        EventPanelSleepClickCb(e);
    }
}

void ui_event_ButtonResetConfirm(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        EventResetConfirm(e);
    }
}

void ui_event_ImageResetBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ScreenListen, LV_SCR_LOAD_ANIM_NONE, 0, 0);
        
        lv_obj_clear_flag(ui_PanelSleep, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_PanelListen, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_PanelReply, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_PanelGet, LV_OBJ_FLAG_HIDDEN);

        if (ui_get_btn_op_group()) {
            lv_group_remove_all_objs(ui_get_btn_op_group());
            lv_group_add_obj(ui_get_btn_op_group(), ui_PanelSleep);
        }
    }
}

void ui_event____initial_actions0(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_PanelSetupWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanelSetupSteps, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    // Use custom green color (#04B900) as primary, orange (#D24B09) as secondary
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_color_hex(0x04B900), lv_color_hex(0xD24B09),
                        false, LV_FONT_DEFAULT);

    lv_indev_t *indev = lv_indev_get_next(NULL);
    if (lv_indev_get_type(indev) == LV_INDEV_TYPE_ENCODER) {
        g_btn_op_group = lv_group_create();
        lv_indev_set_group(indev, g_btn_op_group);
        indev->driver->long_press_time = 1000;
        indev->driver->long_press_repeat_time = 5 * 1000;
    }

    lv_disp_set_theme(dispp, theme);
    ui_ScreenSetup_screen_init();
    ui_ScreenWifiReset_screen_init();
    ui_ScreenListen_screen_init();
    ui_ScreenReset_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_ScreenSetup);
}
