// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt

#ifndef _CHAT_GPT_UI_H
#define _CHAT_GPT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void avatar_speaking_Animation(lv_obj_t *TargetObject, int delay);
void avatar_listening_Animation(lv_obj_t *TargetObject, int delay);
void avatar_stop_animations(void);
// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
extern lv_obj_t *ui_ScreenSetup;
extern lv_obj_t *ui_ImageSetupTextBg;
extern lv_obj_t *ui_PanelSetupWifi;
extern lv_obj_t *ui_LabelSetupWifi;
void ui_event_ImageSetupWifiReset(lv_event_t *e);
extern lv_obj_t *ui_ImageSetupWifiReset;
extern lv_obj_t *ui_PanelSetupSteps;
extern lv_obj_t *ui_LabelSetupStepContent;
extern lv_obj_t *ui_LabelSetupStepTile;
void ui_event_ButtonSetup(lv_event_t *e);
extern lv_obj_t *ui_ButtonSetup;
extern lv_obj_t *ui_LabelSetupBtn;
// SCREEN: ui_ScreenWifiReset
void ui_ScreenWifiReset_screen_init(void);
extern lv_obj_t *ui_ScreenWifiReset;
extern lv_obj_t *ui_LabelWifiResetTitle;
void ui_event_ButtonWifiResetConfirm(lv_event_t *e);
extern lv_obj_t *ui_ButtonWifiResetConfirm;
extern lv_obj_t *ui_LabelSetupBtn1;
void ui_event_ImageWifiResetBack(lv_event_t *e);
extern lv_obj_t *ui_ImageWifiResetBack;
extern lv_obj_t *ui_LabelWifiResetContent;
// SCREEN: ui_ScreenListen
void ui_ScreenListen_screen_init(void);
extern lv_obj_t *ui_ScreenListen;
void ui_event_PanelSleep(lv_event_t *e);
extern lv_obj_t *ui_PanelSleep;
extern lv_obj_t *ui_ImageSleepBody;
extern lv_obj_t *ui_ContainerBigZ;
extern lv_obj_t *ui_ContainerSmallZ;
extern lv_obj_t *ui_PanelListen;
extern lv_obj_t *ui_ImageListenBody;
extern lv_obj_t *ui_PanelGet;
extern lv_obj_t *ui_ImageGetBody;
extern lv_obj_t *ui_PanelReply;
extern lv_obj_t *ui_ImageReplyBg;
extern lv_obj_t *ui_LabelReplyQuestion;
extern lv_obj_t *ui_ImageRelyBody;
extern lv_obj_t *ui_ContainerReplyContent;
extern lv_obj_t *ui_LabelReplyContent;
extern lv_obj_t *ui_LabelListenSpeak;
// SCREEN: ui_ScreenReset
void ui_ScreenReset_screen_init(void);
extern lv_obj_t *ui_ScreenReset;
extern lv_obj_t *ui_LabelResetTitle;
extern lv_obj_t *ui_LabelResetContent;
void ui_event_ButtonResetConfirm(lv_event_t *e);
extern lv_obj_t *ui_ButtonResetConfirm;
extern lv_obj_t *ui_LabelSetupBtn2;
void ui_event_ImageResetBack(lv_event_t *e);
extern lv_obj_t *ui_ImageResetBack;
void ui_event____initial_actions0(lv_event_t *e);
extern lv_obj_t *ui____initial_actions0;

// EVENT: event for ESP32_S3_BOX_Lite
lv_group_t *ui_get_btn_op_group(void);

LV_IMG_DECLARE(ui_img_reset_icon_png);    // assets\reset_icon.png
LV_IMG_DECLARE(ui_img_settings_back_png);    // assets\settings_back.png
LV_IMG_DECLARE(ui_img_sleep_big_z_png);    // assets\sleep_big_z.png
LV_IMG_DECLARE(ui_img_sleep_small_z_png);    // assets\sleep_small_z.png
LV_IMG_DECLARE(ui_img_sleep_mode_png);    // assets\sleep_mode.png
LV_IMG_DECLARE(ui_img_speaker_speaker_0_png);
LV_IMG_DECLARE(ui_img_speaker_speaker_1_png);
LV_IMG_DECLARE(ui_img_speaker_speaker_2_png);
LV_IMG_DECLARE(ui_img_speaker_speaker_3_png);
LV_IMG_DECLARE(ui_img_speaker_speaker_4_png);
LV_IMG_DECLARE(ui_img_speaker_speaker_5_png);
LV_IMG_DECLARE(ui_img_avatar_avatar_0_png);
LV_IMG_DECLARE(ui_img_avatar_avatar_1_png);
LV_IMG_DECLARE(ui_img_avatar_avatar_2_png);
LV_IMG_DECLARE(ui_img_avatar_avatar_3_png);
LV_IMG_DECLARE(ui_img_avatar_avatar_4_png);
LV_IMG_DECLARE(ui_img_avatar_avatar_5_png);

LV_FONT_DECLARE(ui_font_KaiTiCN20);
LV_FONT_DECLARE(ui_font_PingFangEN14);
LV_FONT_DECLARE(ui_font_PingFangEN16);
LV_FONT_DECLARE(ui_font_PingFangEN20);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
